### ISSUE TITLE
Table of contents not working on FAQ page

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#153]
![image](https://user-images.githubusercontent.com/89170008/141931833-eff26fa8-d300-4502-990a-4b9c8fd70e09.png)

**Comment by hintxiv** [comment]
#156 will at least hide the ToC on this page. I believe the issue is because the FAQ layout adds its content dynamically (from each specific question), but I'm not sure how to go about fixing this short of writing a ToC component from scratch.

(Someone who actually understands Hugo might know, though.)

**Comment by ductapeofdoom** [comment]
Note, this issue also effects the BiS and Changes pages. Current proposal is to implement a custom ToC partial for these 3 pages.

**Comment by hintxiv** [comment]
Resolved as of #156
