### ISSUE TITLE
Table of contents does not scroll appropriately on some guides.

### ISSUE THREAD

**Issue by ArcaneDisgea** [The-Balance-FFXIV/glam#167]
Specifically ~~GNB~~DRK, BLM, and BRD basic guides I believe. The TOC follows scrolling and due to the long nature of these guides TOC you cant actually see the bottom of the TOC until you scroll to the absolute bottom of the page

![ttM9TmvtZW](https://user-images.githubusercontent.com/39720490/142249444-9343b1d7-5749-477e-bd0a-7241d4732f5c.gif)
.

**Comment by OHaiDanny** [comment]
I think with the upcoming change that tunes the ToC to only show H1 and H2 tags (instead of H2 an H3) this should massively reduce the height of this.

**Comment by Lunaversitay** [comment]
Might be a good idea to have the table of contents scroll on its own instead of with the website to allow readers to scroll the guide content without losing their place in the table of contents.

Rough mockup of that here: [https://i.lunaversity.dev/4toh2SrGKG.mp4](https://i.lunaversity.dev/4toh2SrGKG.mp4)

**Comment by rexatlanti** [comment]
fixed with #173
